-- Candidate edges remain broad when data is unknown. The bounded solver turns
-- these edges into complete feasible allocation scenarios.
OPEN SCHEMA RECALLNEXT;

CREATE OR REPLACE VIEW V_CANDIDATE_ALLOCATION AS
SELECT
    I.INCIDENT_ID,
    I.INCIDENT_VERSION,
    S.SHIPMENT_ID,
    C.CONTAINER_ID,
    L.LOT_SOURCE_ID,
    L.LOT_CODE,
    L.LOT_SOURCE_ID || ':' || L.LOT_CODE AS LOT_ID,
    CASE
        WHEN C.LOT_ID = L.LOT_ID AND C.HOMOGENEITY_VERIFIED = TRUE
        THEN SC.PICK_QUANTITY_CASES
        ELSE 0
    END AS MIN_QUANTITY_CASES,
    CASE
        WHEN C.LOT_ID = L.LOT_ID AND C.HOMOGENEITY_VERIFIED = TRUE
        THEN SC.PICK_QUANTITY_CASES
        WHEN L.QUANTITY_CASES < SC.PICK_QUANTITY_CASES
        THEN L.QUANTITY_CASES
        ELSE SC.PICK_QUANTITY_CASES
    END AS MAX_QUANTITY_CASES,
    CASE
        WHEN C.LOT_ID = L.LOT_ID AND C.HOMOGENEITY_VERIFIED = TRUE
        THEN 'VERIFIED_HOMOGENEOUS_CONTAINER'
        WHEN C.LOT_ID = L.LOT_ID
        THEN 'MIXED_CONTAINER_KNOWN_COMPONENT'
        WHEN C.LOT_ID IS NULL
        THEN 'UNKNOWN_CONTAINER_LOT'
        ELSE 'MIXED_CONTAINER_OTHER_COMPONENT'
    END AS CANDIDATE_REASON,
    CASE
        WHEN U.CANDIDATE_UNIVERSE_COMPLETE = TRUE THEN 'ELIGIBLE'
        ELSE 'UNRESOLVED_COVERAGE'
    END AS CONSTRAINT_STATUS,
    SC.PICK_RECORD_ID,
    L.SOURCE_EVENT_ID AS LOT_SOURCE_EVENT_ID,
    C.SOURCE_EVENT_ID AS CONTAINER_SOURCE_EVENT_ID,
    U.CANDIDATE_UNIVERSE_COMPLETE,
    CASE WHEN RL.LOT_ID IS NULL THEN FALSE ELSE TRUE END AS IS_RECALLED_LOT
FROM INCIDENT I
JOIN SHIPMENT S
  ON S.PRODUCT_ID = I.PRODUCT_ID
 AND (I.WINDOW_START IS NULL OR S.SHIP_TIME IS NULL OR S.SHIP_TIME >= I.WINDOW_START)
 AND (I.WINDOW_END IS NULL OR S.SHIP_TIME IS NULL OR S.SHIP_TIME <= I.WINDOW_END)
JOIN SHIPMENT_CONTAINER SC
  ON SC.SHIPMENT_ID = S.SHIPMENT_ID
JOIN CONTAINER C
  ON C.CONTAINER_ID = SC.CONTAINER_ID
JOIN LOT L
  ON L.PRODUCT_ID = S.PRODUCT_ID
 AND (C.LOT_ID IS NULL OR C.HOMOGENEITY_VERIFIED = FALSE OR C.LOT_ID = L.LOT_ID)
 AND (L.RECEIVED_AT IS NULL OR S.SHIP_TIME IS NULL OR L.RECEIVED_AT <= S.SHIP_TIME)
 AND (L.LOCATION_ID IS NULL OR C.LOCATION_ID IS NULL OR L.LOCATION_ID = C.LOCATION_ID)
JOIN V_CANDIDATE_UNIVERSE_STATUS U
  ON U.INCIDENT_ID = I.INCIDENT_ID
 AND U.INCIDENT_VERSION = I.INCIDENT_VERSION
LEFT JOIN INCIDENT_RECALLED_LOT RL
  ON RL.INCIDENT_ID = I.INCIDENT_ID
 AND RL.INCIDENT_VERSION = I.INCIDENT_VERSION
 AND RL.LOT_ID = L.LOT_ID;

CREATE OR REPLACE VIEW V_SHIPMENT_CANDIDATE_IMPACT AS
SELECT
    C.INCIDENT_ID,
    C.INCIDENT_VERSION,
    C.SHIPMENT_ID,
    COUNT(DISTINCT C.LOT_ID) AS CANDIDATE_LOT_COUNT,
    CASE
        WHEN SUM(
            CASE WHEN C.IS_RECALLED_LOT = TRUE THEN C.MAX_QUANTITY_CASES ELSE 0 END
        ) > MAX(S.QUANTITY_CASES)
        THEN MAX(S.QUANTITY_CASES)
        ELSE SUM(
            CASE WHEN C.IS_RECALLED_LOT = TRUE THEN C.MAX_QUANTITY_CASES ELSE 0 END
        )
    END AS POSSIBLE_RECALLED_CASES_UPPER_BOUND,
    MAX(S.QUANTITY_CASES) AS HELD_CASES,
    CASE
        WHEN MIN(CASE WHEN C.CANDIDATE_UNIVERSE_COMPLETE = TRUE THEN 1 ELSE 0 END) = 1
        THEN TRUE
        ELSE FALSE
    END AS CANDIDATE_UNIVERSE_COMPLETE
FROM V_CANDIDATE_ALLOCATION C
JOIN SHIPMENT S
  ON S.SHIPMENT_ID = C.SHIPMENT_ID
GROUP BY C.INCIDENT_ID, C.INCIDENT_VERSION, C.SHIPMENT_ID;

CREATE OR REPLACE VIEW V_EVIDENCE_ACTION_IMPACT AS
SELECT
    A.INCIDENT_ID,
    A.INCIDENT_VERSION,
    A.ACTION_ID,
    A.ACTION_TYPE,
    A.TARGET_TYPE,
    A.TARGET_ID,
    A.QUESTION,
    A.ESTIMATED_MINUTES,
    A.AVAILABILITY,
    M.SHIPMENT_ID,
    S.QUANTITY_CASES AS HELD_CASES
FROM EVIDENCE_ACTION A
JOIN ACTION_SHIPMENT M
  ON M.ACTION_ID = A.ACTION_ID
JOIN SHIPMENT S
  ON S.SHIPMENT_ID = M.SHIPMENT_ID;
